# This file contains values from Cookiecutter

default_context:
  project_name: "ai-inspector"
  project_description: "Inspect your AI models visually, find bugs, give feedback ğŸ•µï¸â€â™€ï¸ ğŸ’¬"
  organization: "Giskard AI"
  license: "Apache Software License 2.0"
  minimal_python_version: 3.7
  github_name: "Giskard-AI"
  email: "hello@giskard.ai"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
